/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AceitarTermosRouteImport } from './routes/aceitar-termos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppHistoricoRouteImport } from './routes/_app/historico'
import { Route as AppPerfilRouteImport } from './routes/_app/perfil'
import { Route as AppSobreRouteImport } from './routes/_app/sobre'
import { Route as AppHistoricoIndexRouteImport } from './routes/_app/historico.index'
import { Route as AppHistoricoIdRouteImport } from './routes/_app/historico.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiWebhooksEduzzRouteImport } from './routes/api/webhooks/eduzz'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AceitarTermosRoute = AceitarTermosRouteImport.update({
  id: '/aceitar-termos',
  path: '/aceitar-termos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoricoRoute = AppHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppSobreRoute = AppSobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoricoIndexRoute = AppHistoricoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppHistoricoRoute,
} as any)
const AppHistoricoIdRoute = AppHistoricoIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppHistoricoRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksEduzzRoute = ApiWebhooksEduzzRouteImport.update({
  id: '/api/webhooks/eduzz',
  path: '/api/webhooks/eduzz',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/aceitar-termos': typeof AceitarTermosRoute
  '/login': typeof LoginRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/admin': typeof AppAdminRoute
  '/historico': typeof AppHistoricoRouteWithChildren
  '/perfil': typeof AppPerfilRoute
  '/sobre': typeof AppSobreRoute
  '/historico/$id': typeof AppHistoricoIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/webhooks/eduzz': typeof ApiWebhooksEduzzRoute
  '/historico/': typeof AppHistoricoIndexRoute
}
export interface FileRoutesByTo {
  '/aceitar-termos': typeof AceitarTermosRoute
  '/login': typeof LoginRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/admin': typeof AppAdminRoute
  '/perfil': typeof AppPerfilRoute
  '/sobre': typeof AppSobreRoute
  '/': typeof AppIndexRoute
  '/historico/$id': typeof AppHistoricoIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/webhooks/eduzz': typeof ApiWebhooksEduzzRoute
  '/historico': typeof AppHistoricoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/aceitar-termos': typeof AceitarTermosRoute
  '/login': typeof LoginRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/historico': typeof AppHistoricoRouteWithChildren
  '/_app/perfil': typeof AppPerfilRoute
  '/_app/sobre': typeof AppSobreRoute
  '/_app/': typeof AppIndexRoute
  '/_app/historico/$id': typeof AppHistoricoIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/webhooks/eduzz': typeof ApiWebhooksEduzzRoute
  '/_app/historico/': typeof AppHistoricoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aceitar-termos'
    | '/login'
    | '/privacidade'
    | '/termos'
    | '/admin'
    | '/historico'
    | '/perfil'
    | '/sobre'
    | '/historico/$id'
    | '/api/auth/$'
    | '/api/webhooks/eduzz'
    | '/historico/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/aceitar-termos'
    | '/login'
    | '/privacidade'
    | '/termos'
    | '/admin'
    | '/perfil'
    | '/sobre'
    | '/'
    | '/historico/$id'
    | '/api/auth/$'
    | '/api/webhooks/eduzz'
    | '/historico'
  id:
    | '__root__'
    | '/_app'
    | '/aceitar-termos'
    | '/login'
    | '/privacidade'
    | '/termos'
    | '/_app/admin'
    | '/_app/historico'
    | '/_app/perfil'
    | '/_app/sobre'
    | '/_app/'
    | '/_app/historico/$id'
    | '/api/auth/$'
    | '/api/webhooks/eduzz'
    | '/_app/historico/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AceitarTermosRoute: typeof AceitarTermosRoute
  LoginRoute: typeof LoginRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  TermosRoute: typeof TermosRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiWebhooksEduzzRoute: typeof ApiWebhooksEduzzRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aceitar-termos': {
      id: '/aceitar-termos'
      path: '/aceitar-termos'
      fullPath: '/aceitar-termos'
      preLoaderRoute: typeof AceitarTermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/historico': {
      id: '/_app/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof AppHistoricoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/perfil': {
      id: '/_app/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sobre': {
      id: '/_app/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof AppSobreRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/historico/': {
      id: '/_app/historico/'
      path: '/'
      fullPath: '/historico/'
      preLoaderRoute: typeof AppHistoricoIndexRouteImport
      parentRoute: typeof AppHistoricoRoute
    }
    '/_app/historico/$id': {
      id: '/_app/historico/$id'
      path: '/$id'
      fullPath: '/historico/$id'
      preLoaderRoute: typeof AppHistoricoIdRouteImport
      parentRoute: typeof AppHistoricoRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/eduzz': {
      id: '/api/webhooks/eduzz'
      path: '/api/webhooks/eduzz'
      fullPath: '/api/webhooks/eduzz'
      preLoaderRoute: typeof ApiWebhooksEduzzRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppHistoricoRouteChildren {
  AppHistoricoIdRoute: typeof AppHistoricoIdRoute
  AppHistoricoIndexRoute: typeof AppHistoricoIndexRoute
}

const AppHistoricoRouteChildren: AppHistoricoRouteChildren = {
  AppHistoricoIdRoute: AppHistoricoIdRoute,
  AppHistoricoIndexRoute: AppHistoricoIndexRoute,
}

const AppHistoricoRouteWithChildren = AppHistoricoRoute._addFileChildren(
  AppHistoricoRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppHistoricoRoute: typeof AppHistoricoRouteWithChildren
  AppPerfilRoute: typeof AppPerfilRoute
  AppSobreRoute: typeof AppSobreRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppHistoricoRoute: AppHistoricoRouteWithChildren,
  AppPerfilRoute: AppPerfilRoute,
  AppSobreRoute: AppSobreRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AceitarTermosRoute: AceitarTermosRoute,
  LoginRoute: LoginRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  TermosRoute: TermosRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiWebhooksEduzzRoute: ApiWebhooksEduzzRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
